medicalv2/urls.py
from django.urls import path
from . import views

app_name = 'medical'

urlpatterns = [
    path('patientbasicinfo/<int:student_id>/', views.patient_basic_info, name='patient_basicinfo'),
    path('medicalclearance/<int:student_id>/', views.medicalclearance_view, name='medicalclearance'),
    path('eligibilityform/<int:student_id>/', views.eligibilty_form, name='eligibility_form'),
    path('medicalcertificate/<int:student_id>/', views.med_cert, name='med_cert_for_intrams'),
    path('viewrequest/', views.view_request, name='viewrequest'),
    path('student/request/', views.submit_request, name="request"),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('physicalexam/<int:student_id>/', views.physical_examination, name='physical_exam'),
    path('medicalrequirementstracker/', views.student_medical_requirements_tracker, name='medtracker'),
    path('uploadrequirements/', views.upload_requirements, name='upload_requirements'),
    path('dentalservices/', views.dental_services, name='dentalservice'),
    path('dentalrequest/', views.dental_request, name='dentalrequest'),
    path('dentalschedule/', views.dental_schedule, name='dentalschedule'),
    path('listofpwd/', views.pwd_list, name='pwdlist'),
    path('pwd/<int:student_id>/', views.pwd_detail, name='pwd_detail'),
    path('prescriptions/', views.prescription, name='prescription'),
    path('prescriptionrecords/', views.view_prescription_records, name='prescription_records'),
    path('getstudentname/', views.get_student_name, name='get_student_name'),
    path('emergencyassistance/', views.emergency_asst, name='emergency_asst'),
    path('emergencyassistancerecords', views.view_emergency_health_records, name='emergency_health_records'),
    path('insuranceeligibility/', views.check_insurance_availability, name='insurance_eligibility'),
    # URL for the main transactions view
    path('transactions/', views.transactions_view, name='transactions'),
    path('monthly_transactions/', views.monthly_transactions_view, name='monthly_transactions'),
    path('daily_transactions/', views.daily_transactions_view, name='daily_transactions'),
    # path('yearly/', views.yearly_transactions, name='yearly_transactions'),
    # path('upload/', views.upload_file, name='upload'),
]

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentLife_system/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import transac_search
from .views import approve_alumni_request, claim_alumni_id
from .views import UpdateStatusView

from .views import projects, program_form
from .views import (
    home,
    counseling_app,
    exit_interview,
    individualProfile,
    search_student_info,
    check_date_time_validity,
)
from .views import (
    counseling_app_admin_view,
    ojt_assessment,
    exit_interview_admin_view,
    ojt_assessment_admin_view,
    update_exit_interview_status,
    counselor_scheduler,
    counseling_schedule_admin,
)
from .views import (
    delete_exit_interview_status,
    update_ojt_assessment,
    delete_ojt_assessment,
    check_date_time_validity_for_exit,
    get_ojt_assessment_data,
)
from .views import (
    search_ojt_assessment_request,
    search_exit_interview_request,
    get_exit_interview_request,
    update_counseling_schedule,
    delete_counseling_schedule,
)
from .views import (
    search_student_info_for_individual,
    intake_interview_view,
    search_student_info_for_intake,
    individual_profile_sheet,
)
from .views import (
    home,
    counseling_app,
    exit_interview,
    individualProfile,
    search_student_info,
    check_date_time_validity,
)
from .views import (
    counseling_app_admin_view,
    ojt_assessment,
    exit_interview_admin_view,
    ojt_assessment_admin_view,
    update_exit_interview_status,
)
from .views import (
    delete_exit_interview_status,
    update_ojt_assessment,
    delete_ojt_assessment,
    check_date_time_validity_for_exit,
    get_ojt_assessment_data,
)
from .views import (
    search_ojt_assessment_request,
    search_exit_interview_request,
    get_exit_interview_request,
    update_counseling_schedule,
    delete_counseling_schedule,
)
from .views import (
    search_student_info_for_individual,
    intake_interview_view,
    search_student_info_for_intake,
    individual_profile_sheet,
    guidance_transaction,
    daily_montly_guidance_transaction,
    show_transaction_specific_date,
    sort_counseling_app_admin_view,
    sort_exit_interview_admin_view,
)


app_name = "studentLife_system"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("settings", views.upload_student_data, name="upload_student_data"),
    path("homepage", views.homepage, name="homepage"),
    path("requestgmc", views.requestedgmc, name="requestgmc"),
    path("equipmenttracker", views.equipmentTracker, name="equipmentTracker"),
    path(
        "equipmenttrackerAdmin/",
        views.equipmentTrackerAdmin,
        name="equipmentTrackerAdmin",
    ),
    path(
        "save_equipment_borrowing/",
        views.save_equipment_borrowing,
        name="save_equipment_borrowing",
    ),
    path(
        "update_return_status/", views.update_return_status, name="update_return_status"
    ),
    path("adminmain", views.adminhome, name="adminmain"),
    path("requested-gmc", views.adminRequestedGmc, name="adminRequestedGmc"),
    path("gmc-form", views.gmcform, name="gmcform"),
    path("generate-gmc/<int:request_id>/", views.generateGmc, name="generateGmc"),
    path(
        "transactionreport",
        views.processed_gmc_transactions,
        name="processed_gmc_transactions",
    ),
    path("monthlyCalendar", views.monthlyCalendar, name="monthlyCalendar"),
    path(
        "monthlyCalendarAdmin", views.monthlyCalendarAdmin, name="monthlyCalendarAdmin"
    ),
    path("save-schedule/", views.save_schedule, name="save_schedule"),
    path(
        "update-schedule/<int:schedule_id>/",
        views.update_schedule,
        name="update_schedule",
    ),
    path(
        "delete-schedule/<int:schedule_id>/",
        views.delete_schedule,
        name="delete_schedule",
    ),
    path("addEquipment/", views.addEquipment, name="addEquipment"),
    path("upload/", views.upload_file, name="upload_file"),
    path("display_items/", views.display_items, name="display_items"),
    path("update_status/", UpdateStatusView.as_view(), name="update_status"),
    path("purchased_items/", views.purchased_items, name="purchased_items"),
    path("lnd_file/", views.lnd_file, name="lnd_file"),
    path(
        "display_storage_items/",
        views.display_storage_items,
        name="display_storage_items",
    ),
    path(
        "update_serial_no/<int:storage_id>/",
        views.update_serial_no,
        name="update_serial_no",
    ),
    path(
        "edit/", views.edit_excel_data, name="edit_excel_data"
    ),  # mao ne na lines napuno
    path(
        "update/<int:pk>/", views.update_excel_data, name="update_excel_data"
    ),  # asta ne
    # ALUMNI
    path("id_request/", views.idRequest, name="idRequest"),
    path("search_id/", views.search_id, name="search_id"),
    path("add_alumni/", views.add_alumni, name="add_alumni"),
    path("search_id2/", views.search_id2, name="search_id2"),
    path(
        "graduateTracer_submit",
        views.graduateTracer_submit,
        name="graduateTracer_submit",
    ),
    path("graduatetracer/", views.graduateTracer, name="graduateTracer"),
    path("reunionandevents/", views.alumni_events, name="alumni_events"),
    path("jobfairs/", views.jobfairs, name="jobfairs"),
    path("yearbook/", views.yearbook, name="yearbook"),
    path("search_yearbook/", views.search_yearbook, name="search_yearbook"),
    path(
        "transaction_alumni.html/", views.transaction_alumni, name="transaction_alumni"
    ),
    path("transac_search", transac_search, name="transac_search"),
    path("admin_id_request/", views.admin_id_request, name="admin_idRequest"),
    path(
        "approve_alumni_request/<int:alumni_id>/",
        approve_alumni_request,
        name="approve_alumni_request",
    ),
    path("claim_alumni_id/<int:alumni_id>/", claim_alumni_id, name="claim_alumni_id"),
    path("admin_grad_tracer/", views.admin_gradTracer, name="admin_gradTracer"),
    path("admin_events/", views.admin_events, name="admin_events"),
    path("admin_jobfairs", views.admin_jobfairs, name="admin_jobfairs"),
    path("admin_yearbook", views.admin_yearbook, name="admin_yearbook"),
    # Studentorg
    # LOG-IN
    path("admin_login/", views.admin_login, name="admin_login"),
    path("register_officer/", views.register_officer, name="register_officer"),
    path("officer_login/", views.officer_login, name="officer_login"),
    path("logins/", views.logins, name="logins"),
    # ADMIN
    path("admin_manageofficer/", views.admin_manageofficer, name="admin_manageofficer"),
    path("admin_manageadviser/", views.admin_manageadviser, name="admin_manageadviser"),
    path(
        "admin_managefinancial/",
        views.admin_managefinancial,
        name="admin_managefinancial",
    ),
    path("admin_manageproject/", views.admin_manageproject, name="admin_manageproject"),
    path(
        "admin_manage_accreditations/",
        views.admin_manage_accreditations,
        name="admin_manage_accreditations",
    ),
    path(
        "admin_view_accreditations/",
        views.admin_view_accreditations,
        name="admin_view_accreditations",
    ),
    path(
        "admin_transactionreport/",
        views.admin_transactionreport,
        name="transaction_report",
    ),
    # Certification
    path("FSTLP_certification", views.FSTLP_certification, name="FSTLP_certification"),
    path("SI_certification", views.SI_certification, name="SI_certification"),
    path(
        "THEEQUATIONERS_certification",
        views.THEEQUATIONERS_certification,
        name="THEEQUATIONERS_certification",
    ),
    path("SSG_certification", views.SSG_certification, name="SSG_certification"),
    path(
        "TECHNOCRATS_certification",
        views.TECHNOCRATS_certification,
        name="TECHNOCRATS_certification",
    ),
    # FSTLP
    path("FSTLP_profile", views.FSTLP_profile, name="FSTLP_profile"),
    path("FSTLP_projects", views.FSTLP_projects, name="FSTLP_projects"),
    path("FSTLP_financial", views.FSTLP_financial, name="FSTLP_financial"),
    path("FSTLP_CBL", views.FSTLP_CBL, name="FSTLP_CBL"),
    path("FSTLP_officerdata", views.FSTLP_officerdata, name="FSTLP_officerdata"),
    path("FSTLP_adviserdata", views.FSTLP_adviserdata, name="FSTLP_adviserdata"),
    path("FSTLP_viewproject", views.FSTLP_viewproject, name="FSTLP_viewproject"),
    path("FSTLP_viewfinancial", views.FSTLP_viewfinancial, name="FSTLP_viewfinancial"),
    path("FSTLP_viewofficer", views.FSTLP_viewofficer, name="FSTLP_viewofficer"),
    path("FSTLP_viewadviser", views.FSTLP_viewadviser, name="FSTLP_viewadviser"),
    path("FSTLP_accreditation", views.FSTLP_accreditation, name="FSTLP_accreditation"),
    # SI++
    path("SI_profile", views.SI_profile, name="SI_profile"),
    path("SI_projects", views.SI_projects, name="SI_projects"),
    path("SI_financial", views.SI_financial, name="SI_financial"),
    path("SI_CBL", views.SI_CBL, name="SI_CBL"),
    path("SI_officerdata", views.SI_officerdata, name="SI_officerdata"),
    path("SI_adviserdata", views.SI_adviserdata, name="SI_adviserdata"),
    path("SI_viewproject", views.SI_viewproject, name="SI_viewproject"),
    path("SI_viewfinancial", views.SI_viewfinancial, name="SI_viewfinancial"),
    path("SI_viewadviser", views.SI_viewadviser, name="SI_viewadviser"),
    path("SI_viewofficer", views.SI_viewofficer, name="SI_viewofficer"),
    path("SI_accreditation", views.SI_accreditation, name="SI_accreditation"),
    # THE EQUATIONERS
    path(
        "THEEQUATIONERS_profile",
        views.THEEQUATIONERS_profile,
        name="THEEQUATIONERS_profile",
    ),
    path(
        "THEEQUATIONERS_projects",
        views.THEEQUATIONERS_projects,
        name="THEEQUATIONERS_projects",
    ),
    path(
        "THEEQUATIONERS_financial",
        views.THEEQUATIONERS_financial,
        name="THEEQUATIONERS_financial",
    ),
    path(

templates/adminUser/ppmpTracker/display_storage_items.html
{% extends 'adminUser/adminmain.html' %}
{% load static %}

{% block bodycontent %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'studentlife/main.css'%}">
    <link rel="stylesheet" href="{% static 'studentlife/p_style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
        />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <div class="p-content"><h2>OFFICE OF STUDENT LIFE</h2><br>
    <div>
      <h4><a href="/display_items" class="gray-text">PPMP View</a>
      <span class="orange-text">&nbsp;&gt;&nbsp;Delivered Items</span></h4>
    </div>
    <center><p>Stored Items</p></center>
        <div class="content">
            <table>
                <thead>
                    <tr>
                        <th>Item ID</th>
                        <th>Item</th>
                        <th>Serial Number</th>
                        <th>Unit Price</th> <!-- this is the amount for each item-->
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for storage in storage_items %}
                    <tr>
                        <td>{{ storage.procurement_item.itemid }}</td>
                        <td>{{ storage.procurement_item.item }}</td>
                        <td>{{ storage.serial_no }}</td>
                        <td>{{ storage.procurement_item.unit_price }}</td>
                        <td>
                            {% if not storage.serial_no %}
                            <a href="{% url 'studentLife_system:update_serial_no' storage.id %}">Update Serial No</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">No stored items available</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
{% endblock bodycontent %}

templates/adminUser/ppmpTracker/edit_excel_data.html
{% extends 'adminUser/adminmain.html' %}
{% load static %}

{% block bodycontent %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
        />
        <link rel="stylesheet" href="{% static 'studentlife/main.css'%}">
        <link rel="stylesheet" href="{% static 'studentlife/p_style.css'%}">
        <link rel="stylesheet" href="{% static 'studentlife/ppmp.css'%}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    
       

    
        <style>
            table {
                width: 90%; /* Adjusted to 90% to fit within the page */
                border-collapse: collapse;
                margin-right: 10px; /* Center the table on the page */
            }
            th, td {
                border: 1px solid black;
                padding: 1px; /* Slightly reduced padding for a more compact table */
                text-align: center;
                font-size: 14.5px;
            }
            th {
                background-color: #f2f2f2;
            }
            .success-message {
                color: green;
            }
            .edit-input {
                width: 100%;
                box-sizing: border-box;
            }
            /* Adjusting the widths of individual columns */
            th:nth-child(1), td:nth-child(1) {
                width: 12%;
            }
            th:nth-child(2), td:nth-child(2) {
                width: 8%;
            }
            th:nth-child(3), td:nth-child(3) {
                width: 10%;
            }
            th:nth-child(4), td:nth-child(4) {
                width: 10%;
            }
            th:nth-child(5), td:nth-child(5) {
                width: 10%;
            }
            th:nth-child(6), td:nth-child(6) {
                width: 10%;
            }
            th:nth-child(7), td:nth-child(7) {
                width: 10%;
            }
            th:nth-child(8), td:nth-child(8) {
                width: 10%;
            }
            th:nth-child(9), td:nth-child(9) {
                width: 10%;
            }
            th:nth-child(10), td:nth-child(10) {
                width: 10%;
            }
        </style>
    
</head>
<body>
   
    <div class="p-content">
        <h2>OFFICE OF STUDENT LIFE</h2><br>
        <div>
          <h4><a href="/lnd_file"><span class="gray-text">Learning & Development</span></a>
            <a href="/edit"><span class="orange-text">&nbsp;&gt;&nbsp;L&D View</span></h4></a>
        </div>
            <center><h2>Learning and Development Activities Expenses</h2></center>
            <table>
                <thead>
                    <tr>
                        <th>Title of L & D</th>
                        <th>Frequency</th>
                        <th>Category</th>
                        <th>Expected Number of Participants</th>
                        <th>Duration</th>
                        <th>Registration Fees</th>
                        <th>Travelling Expenses</th>
                        <th>Planned Total Budget</th>
                        <th>Actual Total Budget</th>
                        <th>Variance</th>
                        <th>Remarks</th>
                        <th>Actions</th> 
                    </tr>
                </thead>
                <tbody>
                    {% for data in excel_data %}
                    <tr>
                        <form method="post" action="{% url 'studentLife_system:update_excel_data' data.id %}">
                            {% csrf_token %}
                            <td><input type="text" name="title_of_l_d" value="{{ data.title_of_l_d }}" class="edit-input"></td>
                            <td><input type="text" name="frequency" value="{{ data.frequency }}" class="edit-input"></td>
                            <td><input type="text" name="category" value="{{ data.category }}" class="edit-input"></td>
                            <td><input type="text" name="expected_number_of_participants" value="{{ data.expected_number_of_participants }}" class="edit-input"></td>
                            <td><input type="text" name="duration" value="{{ data.duration }}" class="edit-input"></td>
                            <td><input type="text" name="registration_fees" value="{{ data.registration_fees }}" class="edit-input"></td>
                            <td><input type="text" name="travelling_expenses" value="{{ data.travelling_expenses }}" class="edit-input"></td>
                            <td><input type="text" name="planned_total_budget" value="{{ data.planned_total_budget }}" class="edit-input"></td>
                            <td><input type="text" name="actual_total_budget" value="{{ data.actual_total_budget }}" class="edit-input"></td>
                            <td>
                                {% if data.variance is not None %}
                                    {{ data.variance }}
                                {% endif %}
                            </td>
                            <td>
                            <!--<td><input type="text" name="admin_remarks" value="{{ data.admin_remarks }}" class="edit-input"></td>-->
                            {% if data.admin_remarks %}
                                <input type="text" name="admin_remarks" value="{{ data.admin_remarks }}" class="edit-input">
                            {% else %}
                                <input type="text" name="admin_remarks" value="" class="edit-input">
                            {% endif %}
                            </td>
                            <td><button type="submit">Save</button></td>
                        </form>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="7"><strong>Total</strong></td>
                        <td><strong>{{ total_planned_budget }}</strong></td>
                        <td><strong>{{ total_actual_budget }}</strong></td>
                        <td><strong>{{ total_variance }}</strong></td>
                        <td colspan="2"></td>
                    </tr>
                </tbody>
            </table>
        </div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <center>
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                </center>
                {% endfor %}
            </ul>
         {% endif %}

<script>
     document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        document.getElementById('fileNameDisplay').innerText = fileName;
    });
</script>
        
<script src="{% static 'studentlife/main.js'%}"></script>

</body>
{% endblock bodycontent %}

templates/adminUser/ppmpTracker/learning_dev.html
{% extends 'adminUser/adminmain.html' %}
{% load static %}

{% block bodycontent %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
        />
        
        <link rel="stylesheet" href="{% static 'studentlife/p_style.css'%}">
        <link rel="stylesheet" href="{% static 'studentlife/ppmp.css'%}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        
        <div class="p-content">
            <h2>OFFICE OF STUDENT LIFE</h2><br>
                <div>
                    <h4><a href="/upload"><span class="gray-text">PPMP Tracker</span></a>
                    <span class="orange-text">&nbsp;&gt;&nbsp;Learning & Development</span></h4>
                </div>
               
                <div class="upload-container">
                    <h1>Learning and Development</h1>
                    <form action="{% url 'studentLife_system:lnd_file' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <button type="submit" class="button">Upload</button>
                    </form>
                    <form action="/edit" method="get">
                        <button type="submit" class="button">Display</button>
                    </form>
                </div>
        </div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
         {% endif %}

<script>
     document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        document.getElementById('fileNameDisplay').innerText = fileName;
    });
</script>
        
            
<script src="{% static 'studentlife/main.js'%}"></script>
            
</body>
{% endblock bodycontent %}

templates/adminUser/ppmpTracker/ppmp.html
{% extends 'adminUser/adminmain.html' %}
{% load static %}

{% block bodycontent %}
<link rel="stylesheet" href="{% static 'studentlife/p_style.css' %}">
    <link rel="stylesheet" href="{% static 'studentlife/ppmp.css' %}">
<div class="p-content">
    <h2>Project Procurement Management Plan Tracker</h2><br>
    <div>
        <h4><span class="gray-text">Home</span>
            <span class="orange-text">&nbsp;&gt;&nbsp;PPMP Tracker</span></h4>
    </div>
    <div class="lnd">
        <!--ongoing pa ang pag finalize sa l&d-->
        <h4><a href="{% url 'studentLife_system:lnd_file' %}"><span class="gray-text">Learning & Development</span></a></h4>
    </div>
    <div class="upload-container">
        
        <div class="button-container">
        <form method="post" enctype="multipart/form-data" id="uploadForm">
            {% csrf_token %}
            <label for="fileInput" class="custom-file-label">Choose File</label>
            <input type="file" id="fileInput" name="file" class="custom-file-input">
            <div id="fileNameDisplay" class="file-name-display"></div>
            <button type="submit" class="button">Upload</button>
        </form>
        <form action="{% url 'studentLife_system:display_items' %}" method="get">
            <button type="submit" class="button">Display</button>
        </form>
        </div>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

<script>
    document.getElementById('fileInput').addEventListener('change', function () {
        var fileName = this.value.split('\\').pop();
        document.getElementById('fileNameDisplay').innerText = fileName;
    });
</script>

<script src="{% static 'studentlife/main.js' %}"></script>

{% endblock bodycontent %}

templates/adminUser/ppmpTracker/update_excel_data.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Excel Data</title>
</head>
<body>
    <h1>Update Excel Data</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</body>
</html>

templates/adminUser/ppmpTracker/update_serial_no.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Update Serial Number</title>
    <link rel="stylesheet" href="{% static 'studentlife/main.css'%}">
    <style>
         body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .content {
            background-color: #fff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            width: 90%;
            max-width: 500px;
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        form p {
            width: 100%;
        }

        input[type="text"], input[type="number"], select, textarea {
            width: calc(100% - 20px);
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        @media (max-width: 600px) {
            h2 {
                font-size: 20px;
            }

            input[type="text"], input[type="number"], select, textarea {
                font-size: 14px;
            }

            button {
                font-size: 14px;
            }
        }
    </style>
</head>
<body>
    <div class="content">
        <h2>Update Serial Number for {{ storage_item.procurement_item.item }}</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
</body>
</html>