jobplacement/urls.py
from django.urls import path
from .views import search_suggestions, company_suggestions
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='jobplacement'

urlpatterns = [
    # 
    path('jobplacement/', views.mainpage, name="home"),
    # OJT HIRING THINGS
    path('jobplacement/ojthiring/admin', views.ojt_hiring, name="ojt_hiring"),
    path('jobplacement/ojthiring/admin/assign', views.ojt_assign_student, name='ojthiring_assign'),
    path('jobplacement/ojthiring/more/<str:id>', views.ojt_hiring_info, name='ojthiring_info'),
    path('jobplacement/ojt/requirements/tracker/', views.ojtRequirements_tracker, name="ojt_requirements_tracker"),
    path('jobplacement/ojt/requirements/tracker/update', views.ojt_requirements_accept, name='ojt_requirement_update'),
    path('jobplacement/ojthiring/clear', views.del_ojt, name="del_ojt"),
    path('jobplacement/ojt_requirements/download', views.download_zipped_ojt_templates, name="ojt_requiremets_download"),
    path('jobplacement/ojt/requirements/submit', views.ojt_requirements_submit, name='ojt_requirements_submit'),
    path('jobplacement/ojthiring/delete/<int:id>', views.ojthiring_delete, name="ojt_hiring_delete"),
   
    #   Career Guidance THINGS
    path('jobeplacement/main/', views.seminar, name="seminar_page"),
    # path('jobplacement/new_seminar/', views.newSeminar, name="new_seminar"), # create new seminar
    path('jobplacement/seminar/attendance/manager/<int:id>', views.manage_attendance, name='manage_att'), # manage students with attendance
    path('jobplacement/pending_student_att', views.pend_attendance, name='pending_attendance'), # set attendance to pending
    path('jobplacement/attendance/cancel/<str:id>', views.cancel_pending, name="cancel_pending"), # cancel pending
    path('jobplacement/seminar/attendance/manager/jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending),
    path('jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending, name='attend_all_pending'),
    path('jobplacement/seminar/delete/<int:id>', views.seminar_delete, name='seminar_delete'),

    # Suggestions
    path('suggestions/', search_suggestions.as_view(), name='search_suggestions'),
    path('suggestions/companies', company_suggestions.as_view(), name='company_suggestions'),

    # Transaction Report
    path('jobplacement/report/', views.transRep, name="job_trans_rep"), # report page
    # path('jobplacement/report/creation', views.transaction_creation, name="new_transaction"),
    path('jobplacement/report/print', views.transRep_print, name="rep_print"), # print report

    # Non Academic Issuance
    path('jobplacement/non_acad', views.non_acad_page, name="non_acad"),
    
    # DELETABLE PATHS
    path('jobplacement/login/', views.student_login, name="student_login"),
    path('jobplacement/login/admin/', views.admin_login, name="admin_login"),
    path('jobplacement/signup/', views.student_signup_view, name="student_signup"),
    path('jobplacement/signup/admin', views.admin_signup_view, name="admin_signup"),
    path('jobplacement/logout', views.logout_user, name="logout_user"),
    # ---------------------- STUDENTS PATHS ----------------------------------
    # homescreen sa login og admin    
    path('jobplacement/homepage/admin_student', views.admin_student, name='admin_student'),

    path('jobplacement/ojt/requirements/tracker/view/iframe/<int:id>', views.view_pdf, name='view_pdf'),
    path('jobplacement/upload/', views.file_scrapper, name='scrapper'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicalv2/urls.py
from django.urls import path
from . import views

app_name = 'medical'

urlpatterns = [
    path('patientbasicinfo/<int:student_id>/', views.patient_basic_info, name='patient_basicinfo'),
    path('medicalclearance/<int:student_id>/', views.medicalclearance_view, name='medicalclearance'),
    path('eligibilityform/<int:student_id>/', views.eligibilty_form, name='eligibility_form'),
    path('medicalcertificate/<int:student_id>/', views.med_cert, name='med_cert_for_intrams'),
    path('viewrequest/', views.view_request, name='viewrequest'),
    path('student/request/', views.submit_request, name="request"),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('physicalexam/<int:student_id>/', views.physical_examination, name='physical_exam'),
    path('medicalrequirementstracker/', views.student_medical_requirements_tracker, name='medtracker'),
    path('uploadrequirements/', views.upload_requirements, name='upload_requirements'),
    path('dentalservices/', views.dental_services, name='dentalservice'),
    path('dentalrequest/', views.dental_request, name='dentalrequest'),
    path('dentalschedule/', views.dental_schedule, name='dentalschedule'),
    path('listofpwd/', views.pwd_list, name='pwdlist'),
    path('pwd/<int:student_id>/', views.pwd_detail, name='pwd_detail'),
    path('prescriptions/', views.prescription, name='prescription'),
    path('prescriptionrecords/', views.view_prescription_records, name='prescription_records'),
    path('getstudentname/', views.get_student_name, name='get_student_name'),
    path('emergencyassistance/', views.emergency_asst, name='emergency_asst'),
    path('emergencyassistancerecords', views.view_emergency_health_records, name='emergency_health_records'),
    path('insuranceeligibility/', views.check_insurance_availability, name='insurance_eligibility'),
    # URL for the main transactions view
    path('transactions/', views.transactions_view, name='transactions'),
    path('monthly_transactions/', views.monthly_transactions_view, name='monthly_transactions'),
    path('daily_transactions/', views.daily_transactions_view, name='daily_transactions'),
    # path('yearly/', views.yearly_transactions, name='yearly_transactions'),
    # path('upload/', views.upload_file, name='upload'),
]

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
<!DOCTYPE html>
    <head>
        {% load static %}
        <title>STUDENT LIFE INFORMATION SYSTEM</title>
        <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> -->
        <!-- <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
        /> -->
        <link rel="stylesheet" href="{% static 'styles/index.css'%}?225">
        <script src="{% static 'scripts/jquery.js' %}"></script>
        {% block headcontent %}

        {% endblock headcontent %}

    </head>
    <body>

        <div class="left-side">
            <div class="orange-bar">
                <img src="{% static 'imgs/CTU_logo.png'%}" class="logo">
                <img src="{% static 'imgs/barSort.png'%}" class="bars">
            </div>
            <nav class="side-nav">
                <ul>
                    <li><a href="#" class="studentlife-btn">OFFICE OF STUDENT LIFE 
                        <span class="fas fa-caret-down first"></span>
                    </a>
                        <ul class="studentlife">
                            <li><a href="#">Equipment</a></li>
                            <li><a href="#">Good Moral Certificate Issuance</a></li>
                            <li><a href="#">PPMP Tracker</a></li>
                            <li><a href="#">Monthly Calendar of Activites</a></li>
                        </ul>
                    </li>
                    <li><a href="#" class="scholar-btn">SCHOLARSHIP
                        <span class="fas fa-caret-down second"></span>
                    </a>
                    <ul class="scholar-show">
                        <li><a href="#">Submission of Requirements Tracker</a></li>
                        <li><a href="#">Scholars Profile and Validation</a></li>
                        <li><a href="#">Grade Submission with GPA Computation</a></li>
                        <li><a href="#">Mentorship Program</a></li>
                        <li><a href="#">Admin Cost Liquidation Tracker</a></li>
                        <li><a href="#">CHED Reports Submission</a></li>
                        <li><a href="#">Transaction Reports</a></li>
                    </ul>
                    </li>
                    <li><a href="#" class="jobplace-btn">JOB PLACEMENT
                        <span class="fas fa-caret-down third"></span>    
                    </a>
                    <ul class="jobplace-show">
                            <li><a href="{% url 'jobplacement:ojt_hiring' %}">OJT Hiring</a></li>
                            <li><a href="{% url 'jobplacement:seminar_page' %}">Career Guidance Tracker</a></li>
                            <li><a href="{% url 'jobplacement:ojt_requirements_tracker' %}">OJT Requirements Tracker</a></li>
                            {% if request.user.is_staff %}
                            <li><a href="{% url 'jobplacement:non_acad' %}">Non-Academic Award Issuance</a></li>
                            <li><a href="{% url 'jobplacement:job_trans_rep' %}">Transaction Reports</a></li>
                            {% endif%}
                            {% if request.user.is_superuser %}
                            <li><a href="{% url 'jobplacement:admin_signup' %}">Admin Signup</a></li>
                            {% endif %}
                            {% if request.user.is_staff %}
                            <li><a href="{% url 'jobplacement:student_signup' %}">Student Signup</a></li>
                            {% endif %}
                            <!-- <li><a href="{% url 'jobplacement:admin_login' %}">Admin Login</a></li> -->
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'jobplacement:logout_user' %}">Logout</a></li>
                            {% endif %}
                    </ul>
                    </li>
                    <li><a href="#" class="student_disc-btn">STUDENT DISCIPLINE
                    <span class="fas fa-caret-down fourth"></span>
                    </a>
                    <ul class="student_disc-show">
                        <li><a href="#">Case Profile</a></li>
                        <li><a href="#">Hours Rendered for Community Service Tracker</a></li>
                        <li><a href="#">Good Moral Certificate Issuance</a></li>
                        <li><a href="#">Transaction Reports</a></li>
                        
                    </ul>
                    </li>
                    <li><a href="#" class="guide-btn">GUIDANCE
                    <span class="fas fa-caret-down fifth"></span>
                    </a>
                    <ul class="guide-show">
                        <li><a href="#">Individual Profile with Guidance Concern</a></li>
                        <li><a href="#">Counseling App with Scheduler</a></li>
                        <li><a href="#">Intake Interview</a></li>
                        <li><a href="#">Exit Interview</a></li>
                        <li><a href="#">OJT Assessments/Psychological Issuance</a></li>
                        <li><a href="#">Transaction Reports</a></li>
                    </ul>
                    </li>
                    <li><a href="#" class="alumni-btn">ALUMNI
                    <span class="fas fa-caret-down sixth"></span>
                    </a>
                    <ul class="alumni-show">
                        <li><a href="#">Alumni ID Requests</a></li>
                        <li><a href="#">Graduate Tracer</a></li>
                        <li><a href="#">Alumni Reunion and Events</a></li>
                        <li><a href="#">Job Fairs</a></li>
                        <li><a href="#">Digital Yearbook</a></li>
                        <li><a href="#">Transaction Reports</a></li>
                    </ul>
                    </li>
                    <li><a href="#" class="community-btn">COMMUNITY INVOLVEMENT
                    <span class="fas fa-caret-down seventh"></span>
                    </a>
                    <ul class="community-show">
                        <li><a href="#">Events</a></li>
                        <li><a href="#">CrowdFunding Projects</a></li>
                        <li><a href="#">Donatio App</a></li>
                        <li><a href="#">Transaction Reports</a></li>
                        
                    </ul>
                    </li>
                    <li><a href="#" class="student_org-btn">STUDENT ORGANIZATION
                    <span class="fas fa-caret-down eight"></span>
                    </a>
                        <ul class="student_org-show">
                            <li><a href="#">Org Profile</a></li>
                            <li><a href="#">Projects and Accomplishments</a></li>
                            <li><a href="#">Financial Statements Reports</a></li>
                            <li><a href="#">Accreditation Application</a></li>
                            <li><a href="#">Transaction Reports</a></li>
                        </ul>
                    </li>
                    <li><a href="#" class="medical-btn">MEDICAL
                        <span class="fas fa-caret-down ninth"></span>
                        </a>
                        <ul class="medical-show">
                            <li><a href="#">Patient Profile</a></li>
                            <li><a href="#">Student Medical Requirements Tracker</a></li>
                            <li><a href="#">Emergency Health Assistance</a></li>
                            <li><a href="#">PWD Profile</a></li>
                            <li><a href="#">Dental Services</a></li>
                            <li><a href="#">Medical Clearance Issuance</a></li>
                            <li><a href="#">Prescription Issuance</a></li>
                            <li><a href="#">Transaction Reports</a></li>
                            <li><a href="{% url 'jobplacement:del_ojt' %}">Ayaw E click</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="right-side">
            <div class="search-container">
                <div class="search-icon">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </div>
                <input type="text" placeholder="Search...">
                
                <p> {{ request.user.firstname }} {{ request.user.lastname }}
                    {% if request.user.is_superuser %}
                        (Superuser)
                    {% elif request.user.is_staff %}
                        (Staff)
                    {% else %}
                        (Student)
                    {% endif %}
                </p>
                <div id="message-container">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="message">
                                {% if message.tags == 'success' %}
                                    <img src="{% static 'imgs/check.png' %}" alt="check" class="message-icon">
                                {% elif message.tags == 'error' %}
                                    <img src="{% static 'imgs/wrong.png' %}" alt="wrong" class="message-icon">
                                {% elif message.tags == 'info' %}
                                    <img src="{% static 'imgs/lightbulb.png' %}" alt="bulb" class="message-icon">
                                {% endif %}
                                <p>{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>                
            </div>
            <main class="main_content">
                {% block bodycontent %}

                {% endblock bodycontent %}
            </main>
        </div>
        
        

       <script src="{% static 'scripts/main.js'%}"></script>
       <script src="{% static 'scripts/message.js'%}"></script>
    </body>
    
</html>