jobplacement/urls.py
from django.urls import path
from .views import search_suggestions, company_suggestions
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='jobplacement'

urlpatterns = [
    # 
    path('jobplacement/', views.mainpage, name="home"),
    # OJT HIRING THINGS
    path('jobplacement/ojthiring/admin', views.ojt_hiring, name="ojt_hiring"),
    path('jobplacement/ojthiring/admin/assign', views.ojt_assign_student, name='ojthiring_assign'),
    path('jobplacement/ojthiring/more/<str:id>', views.ojt_hiring_info, name='ojthiring_info'),
    path('jobplacement/ojt/requirements/tracker/', views.ojtRequirements_tracker, name="ojt_requirements_tracker"),
    path('jobplacement/ojt/requirements/tracker/update', views.ojt_requirements_accept, name='ojt_requirement_update'),
    path('jobplacement/ojthiring/clear', views.del_ojt, name="del_ojt"),
    path('jobplacement/ojt_requirements/download', views.download_zipped_ojt_templates, name="ojt_requiremets_download"),
    path('jobplacement/ojt/requirements/submit', views.ojt_requirements_submit, name='ojt_requirements_submit'),
    path('jobplacement/ojthiring/delete/<int:id>', views.ojthiring_delete, name="ojt_hiring_delete"),
   
    #   Career Guidance THINGS
    path('jobeplacement/main/', views.seminar, name="seminar_page"),
    # path('jobplacement/new_seminar/', views.newSeminar, name="new_seminar"), # create new seminar
    path('jobplacement/seminar/attendance/manager/<int:id>', views.manage_attendance, name='manage_att'), # manage students with attendance
    path('jobplacement/pending_student_att', views.pend_attendance, name='pending_attendance'), # set attendance to pending
    path('jobplacement/attendance/cancel/<str:id>', views.cancel_pending, name="cancel_pending"), # cancel pending
    path('jobplacement/seminar/attendance/manager/jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending),
    path('jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending, name='attend_all_pending'),
    path('jobplacement/seminar/delete/<int:id>', views.seminar_delete, name='seminar_delete'),

    # Suggestions
    path('suggestions/', search_suggestions.as_view(), name='search_suggestions'),
    path('suggestions/companies', company_suggestions.as_view(), name='company_suggestions'),

    # Transaction Report
    path('jobplacement/report/', views.transRep, name="job_trans_rep"), # report page
    # path('jobplacement/report/creation', views.transaction_creation, name="new_transaction"),
    path('jobplacement/report/print', views.transRep_print, name="rep_print"), # print report

    # Non Academic Issuance
    path('jobplacement/non_acad', views.non_acad_page, name="non_acad"),
    
    # DELETABLE PATHS
    path('jobplacement/login/', views.student_login, name="student_login"),
    path('jobplacement/login/admin/', views.admin_login, name="admin_login"),
    path('jobplacement/signup/', views.student_signup_view, name="student_signup"),
    path('jobplacement/signup/admin', views.admin_signup_view, name="admin_signup"),
    path('jobplacement/logout', views.logout_user, name="logout_user"),
    # ---------------------- STUDENTS PATHS ----------------------------------
    # homescreen sa login og admin    
    path('jobplacement/homepage/admin_student', views.admin_student, name='admin_student'),

    path('jobplacement/ojt/requirements/tracker/view/iframe/<int:id>', views.view_pdf, name='view_pdf'),
    path('jobplacement/upload/', views.file_scrapper, name='scrapper'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicalv2/urls.py
from django.urls import path
from . import views

app_name = 'medical'

urlpatterns = [
    path('patientbasicinfo/<int:student_id>/', views.patient_basic_info, name='patient_basicinfo'),
    path('medicalclearance/<int:student_id>/', views.medicalclearance_view, name='medicalclearance'),
    path('eligibilityform/<int:student_id>/', views.eligibilty_form, name='eligibility_form'),
    path('medicalcertificate/<int:student_id>/', views.med_cert, name='med_cert_for_intrams'),
    path('viewrequest/', views.view_request, name='viewrequest'),
    path('student/request/', views.submit_request, name="request"),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('physicalexam/<int:student_id>/', views.physical_examination, name='physical_exam'),
    path('medicalrequirementstracker/', views.student_medical_requirements_tracker, name='medtracker'),
    path('uploadrequirements/', views.upload_requirements, name='upload_requirements'),
    path('dentalservices/', views.dental_services, name='dentalservice'),
    path('dentalrequest/', views.dental_request, name='dentalrequest'),
    path('dentalschedule/', views.dental_schedule, name='dentalschedule'),
    path('listofpwd/', views.pwd_list, name='pwdlist'),
    path('pwd/<int:student_id>/', views.pwd_detail, name='pwd_detail'),
    path('prescriptions/', views.prescription, name='prescription'),
    path('prescriptionrecords/', views.view_prescription_records, name='prescription_records'),
    path('getstudentname/', views.get_student_name, name='get_student_name'),
    path('emergencyassistance/', views.emergency_asst, name='emergency_asst'),
    path('emergencyassistancerecords', views.view_emergency_health_records, name='emergency_health_records'),
    path('insuranceeligibility/', views.check_insurance_availability, name='insurance_eligibility'),
    # URL for the main transactions view
    path('transactions/', views.transactions_view, name='transactions'),
    path('monthly_transactions/', views.monthly_transactions_view, name='monthly_transactions'),
    path('daily_transactions/', views.daily_transactions_view, name='daily_transactions'),
    # path('yearly/', views.yearly_transactions, name='yearly_transactions'),
    # path('upload/', views.upload_file, name='upload'),
]

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentLife_system/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import transac_search
from .views import approve_alumni_request, claim_alumni_id
from .views import UpdateStatusView

from .views import projects, program_form
from .views import (
    home,
    counseling_app,
    exit_interview,
    individualProfile,
    search_student_info,
    check_date_time_validity,
)
from .views import (
    counseling_app_admin_view,
    ojt_assessment,
    exit_interview_admin_view,
    ojt_assessment_admin_view,
    update_exit_interview_status,
    counselor_scheduler,
    counseling_schedule_admin,
)
from .views import (
    delete_exit_interview_status,
    update_ojt_assessment,
    delete_ojt_assessment,
    check_date_time_validity_for_exit,
    get_ojt_assessment_data,
)
from .views import (
    search_ojt_assessment_request,
    search_exit_interview_request,
    get_exit_interview_request,
    update_counseling_schedule,
    delete_counseling_schedule,
)
from .views import (
    search_student_info_for_individual,
    intake_interview_view,
    search_student_info_for_intake,
    individual_profile_sheet,
)
from .views import (
    home,
    counseling_app,
    exit_interview,
    individualProfile,
    search_student_info,
    check_date_time_validity,
)
from .views import (
    counseling_app_admin_view,
    ojt_assessment,
    exit_interview_admin_view,
    ojt_assessment_admin_view,
    update_exit_interview_status,
)
from .views import (
    delete_exit_interview_status,
    update_ojt_assessment,
    delete_ojt_assessment,
    check_date_time_validity_for_exit,
    get_ojt_assessment_data,
)
from .views import (
    search_ojt_assessment_request,
    search_exit_interview_request,
    get_exit_interview_request,
    update_counseling_schedule,
    delete_counseling_schedule,
)
from .views import (
    search_student_info_for_individual,
    intake_interview_view,
    search_student_info_for_intake,
    individual_profile_sheet,
    guidance_transaction,
    daily_montly_guidance_transaction,
    show_transaction_specific_date,
    sort_counseling_app_admin_view,
    sort_exit_interview_admin_view,
)


app_name = "studentLife_system"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("settings", views.upload_student_data, name="upload_student_data"),
    path("homepage", views.homepage, name="homepage"),
    path("requestgmc", views.requestedgmc, name="requestgmc"),
    path("equipmenttracker", views.equipmentTracker, name="equipmentTracker"),
    path(
        "equipmenttrackerAdmin/",
        views.equipmentTrackerAdmin,
        name="equipmentTrackerAdmin",
    ),
    path(
        "save_equipment_borrowing/",
        views.save_equipment_borrowing,
        name="save_equipment_borrowing",
    ),
    path(
        "update_return_status/", views.update_return_status, name="update_return_status"
    ),
    path("adminmain", views.adminhome, name="adminmain"),
    path("requested-gmc", views.adminRequestedGmc, name="adminRequestedGmc"),
    path("gmc-form", views.gmcform, name="gmcform"),
    path("generate-gmc/<int:request_id>/", views.generateGmc, name="generateGmc"),
    path(
        "transactionreport",
        views.processed_gmc_transactions,
        name="processed_gmc_transactions",
    ),
    path("monthlyCalendar", views.monthlyCalendar, name="monthlyCalendar"),
    path(
        "monthlyCalendarAdmin", views.monthlyCalendarAdmin, name="monthlyCalendarAdmin"
    ),
    path("save-schedule/", views.save_schedule, name="save_schedule"),
    path(
        "update-schedule/<int:schedule_id>/",
        views.update_schedule,
        name="update_schedule",
    ),
    path(
        "delete-schedule/<int:schedule_id>/",
        views.delete_schedule,
        name="delete_schedule",
    ),
    path("addEquipment/", views.addEquipment, name="addEquipment"),
    path("upload/", views.upload_file, name="upload_file"),
    path("display_items/", views.display_items, name="display_items"),
    path("update_status/", UpdateStatusView.as_view(), name="update_status"),
    path("purchased_items/", views.purchased_items, name="purchased_items"),
    path("lnd_file/", views.lnd_file, name="lnd_file"),
    path(
        "display_storage_items/",
        views.display_storage_items,
        name="display_storage_items",
    ),
    path(
        "update_serial_no/<int:storage_id>/",
        views.update_serial_no,
        name="update_serial_no",
    ),
    path(
        "edit/", views.edit_excel_data, name="edit_excel_data"
    ),  # mao ne na lines napuno
    path(
        "update/<int:pk>/", views.update_excel_data, name="update_excel_data"
    ),  # asta ne
    # ALUMNI
    path("id_request/", views.idRequest, name="idRequest"),
    path("search_id/", views.search_id, name="search_id"),
    path("add_alumni/", views.add_alumni, name="add_alumni"),
    path("search_id2/", views.search_id2, name="search_id2"),
    path(
        "graduateTracer_submit",
        views.graduateTracer_submit,
        name="graduateTracer_submit",
    ),
    path("graduatetracer/", views.graduateTracer, name="graduateTracer"),
    path("reunionandevents/", views.alumni_events, name="alumni_events"),
    path("jobfairs/", views.jobfairs, name="jobfairs"),
    path("yearbook/", views.yearbook, name="yearbook"),
    path("search_yearbook/", views.search_yearbook, name="search_yearbook"),
    path(
        "transaction_alumni.html/", views.transaction_alumni, name="transaction_alumni"
    ),
    path("transac_search", transac_search, name="transac_search"),
    path("admin_id_request/", views.admin_id_request, name="admin_idRequest"),
    path(
        "approve_alumni_request/<int:alumni_id>/",
        approve_alumni_request,
        name="approve_alumni_request",
    ),
    path("claim_alumni_id/<int:alumni_id>/", claim_alumni_id, name="claim_alumni_id"),
    path("admin_grad_tracer/", views.admin_gradTracer, name="admin_gradTracer"),
    path("admin_events/", views.admin_events, name="admin_events"),
    path("admin_jobfairs", views.admin_jobfairs, name="admin_jobfairs"),
    path("admin_yearbook", views.admin_yearbook, name="admin_yearbook"),
    # Studentorg
    # LOG-IN
    path("admin_login/", views.admin_login, name="admin_login"),
    path("register_officer/", views.register_officer, name="register_officer"),
    path("officer_login/", views.officer_login, name="officer_login"),
    path("logins/", views.logins, name="logins"),
    # ADMIN
    path("admin_manageofficer/", views.admin_manageofficer, name="admin_manageofficer"),
    path("admin_manageadviser/", views.admin_manageadviser, name="admin_manageadviser"),
    path(
        "admin_managefinancial/",
        views.admin_managefinancial,
        name="admin_managefinancial",
    ),
    path("admin_manageproject/", views.admin_manageproject, name="admin_manageproject"),
    path(
        "admin_manage_accreditations/",
        views.admin_manage_accreditations,
        name="admin_manage_accreditations",
    ),
    path(
        "admin_view_accreditations/",
        views.admin_view_accreditations,
        name="admin_view_accreditations",
    ),
    path(
        "admin_transactionreport/",
        views.admin_transactionreport,
        name="transaction_report",
    ),
    # Certification
    path("FSTLP_certification", views.FSTLP_certification, name="FSTLP_certification"),
    path("SI_certification", views.SI_certification, name="SI_certification"),
    path(
        "THEEQUATIONERS_certification",
        views.THEEQUATIONERS_certification,
        name="THEEQUATIONERS_certification",
    ),
    path("SSG_certification", views.SSG_certification, name="SSG_certification"),
    path(
        "TECHNOCRATS_certification",
        views.TECHNOCRATS_certification,
        name="TECHNOCRATS_certification",
    ),
    # FSTLP
    path("FSTLP_profile", views.FSTLP_profile, name="FSTLP_profile"),
    path("FSTLP_projects", views.FSTLP_projects, name="FSTLP_projects"),
    path("FSTLP_financial", views.FSTLP_financial, name="FSTLP_financial"),
    path("FSTLP_CBL", views.FSTLP_CBL, name="FSTLP_CBL"),
    path("FSTLP_officerdata", views.FSTLP_officerdata, name="FSTLP_officerdata"),
    path("FSTLP_adviserdata", views.FSTLP_adviserdata, name="FSTLP_adviserdata"),
    path("FSTLP_viewproject", views.FSTLP_viewproject, name="FSTLP_viewproject"),
    path("FSTLP_viewfinancial", views.FSTLP_viewfinancial, name="FSTLP_viewfinancial"),
    path("FSTLP_viewofficer", views.FSTLP_viewofficer, name="FSTLP_viewofficer"),
    path("FSTLP_viewadviser", views.FSTLP_viewadviser, name="FSTLP_viewadviser"),
    path("FSTLP_accreditation", views.FSTLP_accreditation, name="FSTLP_accreditation"),
    # SI++
    path("SI_profile", views.SI_profile, name="SI_profile"),
    path("SI_projects", views.SI_projects, name="SI_projects"),
    path("SI_financial", views.SI_financial, name="SI_financial"),
    path("SI_CBL", views.SI_CBL, name="SI_CBL"),
    path("SI_officerdata", views.SI_officerdata, name="SI_officerdata"),
    path("SI_adviserdata", views.SI_adviserdata, name="SI_adviserdata"),
    path("SI_viewproject", views.SI_viewproject, name="SI_viewproject"),
    path("SI_viewfinancial", views.SI_viewfinancial, name="SI_viewfinancial"),
    path("SI_viewadviser", views.SI_viewadviser, name="SI_viewadviser"),
    path("SI_viewofficer", views.SI_viewofficer, name="SI_viewofficer"),
    path("SI_accreditation", views.SI_accreditation, name="SI_accreditation"),
    # THE EQUATIONERS
    path(
        "THEEQUATIONERS_profile",
        views.THEEQUATIONERS_profile,
        name="THEEQUATIONERS_profile",
    ),
    path(
        "THEEQUATIONERS_projects",
        views.THEEQUATIONERS_projects,
        name="THEEQUATIONERS_projects",
    ),
    path(
        "THEEQUATIONERS_financial",
        views.THEEQUATIONERS_financial,
        name="THEEQUATIONERS_financial",
    ),
    path(

templates/guidance/admin/access_violation.html
{% extends "guidance/admin/main.html" %}
{% load static %}
{% block title %}Access Violation{% endblock %}
{% block headcontent %}
{% endblock %}
{% block bodycontent %}
    <h2>{{info}}</h2>
{% endblock %}

templates/guidance/admin/goodmoral.html
{% extends "guidance/admin/main.html" %}
{% load static %}
{% block headcontent %}
    <link rel="stylesheet" href="{% static 'guidance/stylesheet/good_moral no nav.css'%}">
{% endblock %}

{% block bodycontent %}
    <div class="certificate" id="pagecontainer">
        <div class="logo_content">
            <img class="logo1" src="{% static 'guidance/assets/CTU_logo.png'%}" alt="CTU Logo">
            <div class="header">
                <p class="Republique">REPUBLIC OF THE PHILIPPINES</p>
                <p class="cebu">CEBU TECHNOLOGICAL UNIVERSITY ARGAO CAMPUS</p>
                <p>ARGAO CAMPUS</p>
                <p>Ed Kintanar Street Lamacan, Argao Cebu Philippines</p>
                <p>Website:<a href="">http//www.argao.ctu.edu.ph</a> E-mail: cdargao@ctud.edu.ph</p>
                <p>Phone No: (032) 485-8290/485-5109 loc 1700Fax NO (032)4858-290</p>
            </div>
            <img class="logo2" src="{% static 'guidance/assets/asean.png'%}" alt="ASEAN Logo">
        </div>
        <hr>
        <div class="title">
            <h2>OFFICE OF STUDENT LIFE<br>
                GUIDANCE SERVICES CENTER<br>
                CERTICATION OF GOOD MORAL CHARACTER
            </h2>
        </div>
        <div class="content">
            <br>
            <p id="starting">To Whom It May Concern:</p>
            <br>
            <p> This is to certify that <strong>{{value.name}}</strong> is a bonafide student of Cebu Technological
                University-Argao Campus during the school year 2023-2024 (4th Year , 2nd Semenster) taking
                <strong>{{value.course}}</strong>
            </p>
            <br>
            <p>During his stay in this institution, we have not found any record to show that he committed any act
                contrary to the rules and regulations of the school.</p>
            <br>
            <p>This is also to certify that upon assessment, the person whose name mentioned above is emotionally fit to
                undergo intership.</p>
            <br>
            <p>This certification is issued on <strong>{{value.date}}</strong> for the purpose of his <strong>{{value.type}}</strong>.</p>
        </div>
        <br>
        <div class="signature">
            <div class="guidance">
                <p class="names"><strong>RHEA JANE L. CAYNILA, RPm, RGC</strong></p>
                <p>Guidance Service Coordinator</p>
            </div>
            <br>
            <div class="guidance">
                <p class="names"><strong>MELANIE R. ALBARRACIN</strong></p>
                <p>Dean, Student Life</p>
            </div>
        </div>
    </div>
    <button id="printbutton" class="print">Print</button>
    <script src="{% static 'guidance/scripts/good_moral.js'%}"></script>
{% endblock %}

templates/guidance/admin/main.html
{% load static %}

<!DOCTYPE html>

<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'guidance/stylesheet/main.css'%}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="shortcut icon" type="x-icon" href="{% static 'images/CTU_logo.png' %}">
  <title>STUDENT LIFE INFORMATION SYSTEM</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% block headcontent %}

  {% endblock headcontent %}

</head>

<body>
  <div class="left-side">
    <div class="orange-bar">
      <img src="{% static 'guidance/assets/CTU_logo.png'%}" class="logo">
      <img src="{% static 'guidance/assets/barSort.png'%}" class="bars">
    </div>
    <nav class="side-nav">
      <ul>
        <li><a href="#" class="studentlife-btn">OFFICE OF STUDENT LIFE
            <span class="fas fa-caret-down first"></span>
          </a>
          <ul class="studentlife">
            <li><a href="/equipmenttracker">Equipment Tracker</a></li>
            <li><a href="/requestgmc">Good Moral Certificate Issuance</a></li>
            <li><a href="#">PPMP Tracker</a></li>
            <li><a href="/monthlyCalendar">Monthly Calendar of Activites</a></li>
          </ul>
        </li>
        <li><a href="#" class="scholar-btn">SCHOLARSHIP
            <span class="fas fa-caret-down second"></span>
          </a>
          <ul class="scholar-show">
            <li><a href="#">Submission of Requirements Tracker</a></li>
            <li><a href="#">Scholars Profile and Validation</a></li>
            <li><a href="#">Grade Submission with GPA Computation</a></li>
            <li><a href="#">Mentorship Program</a></li>
            <li><a href="#">Admin Cost Liquidation Tracker</a></li>
            <li><a href="#">CHED Reports Submission</a></li>
            <li><a href="#">Transaction Reports</a></li>
          </ul>
        </li>
        <li><a href="#" class="jobplace-btn">JOB PLACEMENT
            <span class="fas fa-caret-down third"></span>
          </a>
          <ul class="jobplace-show">
            <li><a href="{% url 'jobplacement:ojt_hiring' %}">OJT Hiring</a></li>
            <li><a href="{% url 'jobplacement:seminar_page' %}">Career Guidance Tracker</a></li>
            <li><a href="{% url 'jobplacement:ojt_requirements_tracker' %}">OJT Requirements Tracker</a></li>
            {% if request.user.is_staff %}
            <li><a href="{% url 'jobplacement:non_acad' %}">Non-Academic Award Issuance</a></li>
            <li><a href="{% url 'jobplacement:job_trans_rep' %}">Transaction Reports</a></li>
            {% endif%}
            {% if request.user.is_superuser %}
            <li><a href="{% url 'jobplacement:admin_signup' %}">Admin Signup</a></li>
            {% endif %}
            {% if request.user.is_staff %}
            <li><a href="{% url 'jobplacement:student_signup' %}">Student Signup</a></li>
            {% endif %}
            <!-- <li><a href="{% url 'jobplacement:admin_login' %}">Admin Login</a></li> -->
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'jobplacement:logout_user' %}">Logout</a></li>
            {% endif %}
          </ul>
        </li>
        <li><a href="#" class="student_disc-btn">STUDENT DISCIPLINE
            <span class="fas fa-caret-down fourth"></span>
          </a>
          <ul class="student_disc-show">
            <li><a href="#">Case Profile</a></li>
            <li><a href="#">Hours Rendered for Community Service Tracker</a></li>
            <li><a href="#">Good Moral Certificate Issuance</a></li>
            <li><a href="#">Transaction Reports</a></li>

          </ul>
        </li>
        <li><a href="#" class="guide-btn">GUIDANCE
            <span class="fas fa-caret-down fifth"></span>
          </a>
          <ul class="guide-show">
            <li><a href="{% url 'studentLife_system:Counseling App With Scheduler Admin View'%}">Counseling App with
                Scheduler</a></li>
            <li><a href="{% url 'studentLife_system:Intake Interview' %}">Intake Interview</a></li>
            <li><a href="{% url 'studentLife_system:Exit Interview Admin View'%}">Exit Interview</a></li>
            <li><a href="{% url 'studentLife_system:OJT Assessment Admin View'%}">OJT Assessments/Psychological
                Issuance</a></li>
            <li><a href="{% url 'studentLife_system:guidance_transaction' %}">Transaction Reports</a></li>
          </ul>
        </li>
        <li><a href="#" class="alumni-btn">ALUMNI
            <span class="fas fa-caret-down sixth"></span>
          </a>
          <ul class="alumni-show">
            <li><a href="{% url 'studentLife_system:idRequest' %}">Alumni ID Requests</a></li>
            <li><a href="{% url 'studentLife_system:graduateTracer' %}">Graduate Tracer</a></li>
            <li><a href="{% url 'studentLife_system:alumni_events' %}">Alumni Reunion and Events</a></li>
            <li><a href="{% url 'studentLife_system:jobfairs' %}">Job Fairs</a></li>
            <li><a href="{% url 'studentLife_system:yearbook' %}">Digital Yearbook</a></li>
          </ul>
        </li>
        <li><a href="#" class="community-btn">COMMUNITY INVOLVEMENT
            <span class="fas fa-caret-down seventh"></span>
          </a>
          <ul class="community-show">
            {% if user %}
            <li><a href="{% url 'studentLife_system:program-form' %}">Events (Admin)</a></li>
            <li><a href="{% url 'studentLife_system:project-form' %}">Crowd Funding Project (Admin)</a></li>
            {% else %}
            {% endif %}
            <li><a href="{% url 'studentLife_system:programs' %}">Events</a></li>
            <li><a href="{% url 'studentLife_system:projects' %}">CrowdFunding Projects</a></li>
            {% if user %}
            <li><a href="{% url 'studentLife_system:donation-validate' %}">Donation Validates</a></li>
            <li><a href="{% url 'studentLife_system:donation_dashboard' %}">Donations</a></li>
            <li><a href="{% url 'studentLife_system:reports' %}">Transaction Reports</a></li>
            {% else %}
            {% endif %}

          </ul>
        </li>
        <li><a href="#" class="student_org-btn">STUDENT ORGANIZATION
            <span class="fas fa-caret-down eight"></span>
          </a>
          <ul class="student_org-show">
            <li><a href="#">Org Profile</a></li>
            <li><a href="#">Projects and Accomplishments</a></li>
            <li><a href="#">Financial Statements Reports</a></li>
            <li><a href="#">Accreditation Application</a></li>
            <li><a href="#">Transaction Reports</a></li>
          </ul>
        </li>
        <li><a href="#" class="medical-btn">MEDICAL
            <span class="fas fa-caret-down ninth"></span>
          </a>
          <ul class="medical-show">
            <li><a href="{% url 'medicalv2:upload_requirements' %}">Student Medical Requirements Tracker</a></li>
            <li><a href="{% url 'medicalv2:request' %}">Medical Form Request</a></li>
            <li><a href="{% url 'medicalv2:dentalservice' %}">Dental Services</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
  <div class="right-side">
    <div class="search-container">
      <div class="search-icon">
        <i class="fa-solid fa-magnifying-glass"></i>
      </div>
      <input type="text" placeholder="Search...">
    </div>
    <main class="main_content">
      {% block bodycontent %}{% endblock %}
    </main>
  </div>


  <script src="{% static 'guidance/scripts/main.js'%}"></script>
</body>

</html>